# Generated by Django 5.1.2 on 2024-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=100)),
                ('server_ip', models.GenericIPAddressField()),
                ('status', models.CharField(default='stopped', max_length=20)),
                ('cpu_usage', models.FloatField(default=0.0)),
                ('ram_usage', models.FloatField(default=0.0)),
            ],
        ),
    ]
